---
# tasks/common.yml - Fixed repository issues

# System prerequisites
- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Remove swap entry from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s+sw\s+.*)$'
    line: '# \1'
    backrefs: true
    state: present

- name: Enable required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel modules to load at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0***'

- name: Configure kernel parameters for Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - {key: "****", value: "*"}
    - {key: "*****", value: "*"}
    - {key: "************", value: "*"}

# Install containerd as the container runtime - FIXED
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Create Docker keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0***'

- name: Add Docker GPG key (fixed method)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0***'

- name: Import Docker GPG key to keyring
  shell: gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository (fixed method)
  apt_repository:
    repo: "deb [***=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: true

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0***'

- name: Configure containerd
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Update containerd configuration to use systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    state: present

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true

# Install Kubernetes components - FIXED
- name: Create Kubernetes keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0***'

- name: Add Kubernetes GPG key (fixed method)
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /tmp/k8s.key
    mode: '0***'

- name: Import Kubernetes GPG key to keyring
  shell: gpg --dearmor < /tmp/k8s.key > /etc/apt/keyrings/kubernetes.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes.gpg

- name: Add Kubernetes repository (fixed method)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold Kubernetes packages at current version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: true