---
- name: Copy join command to worker
  copy:
    src: ./join-command.sh
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0***'

- name: Join the Kubernetes cluster
  command: /tmp/kubeadm_join_cmd.sh
  register: join_result
  failed_when: "'This node has joined the cluster' not in join_result.stdout and join_result.rc != 0"

- name: Start kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: true
